---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-example-com
  namespace: boardgame
spec:
  secretName: local-example-com-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.odennav.com"
  dnsNames:
  - "odennav.com"
  - "*.odennav.com"
