---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-odennav-com
  namespace: default
spec:
  secretName: local-odennav-com-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.local.odennav.com"
  dnsNames:
  - "local.odennav.com"
  - "*.local.odennav.com"
